<?php
/*
Clase modelo: SEDESEM_299
Descripción: esta clase se creó para poder utilizar los datos de esta tabla.
*/
namespace App;

use Illuminate\Database\Eloquent\Model;
use Propaganistas\LaravelFakeId\RoutesWithFakeIds;

class SEDESEM_299 extends Model
{
    use RoutesWithFakeIds;
    
    protected $table = "SEDESEM_299";
    protected  $primaryKey = 'FOLIO';
    public $timestamps = false;
    public $incrementing = false;
    protected $fillable = [
    		'N_PERIODO',
    		'CVE_PROGRAMA',
    		'FOLIO',
    		'FOLIO_RELACIONADO',
    		'ES_JEFA',
    		'CVE_PARENTESCO',
    		'INDIGENA',
    		'HABLA_LENGUA_I',
    		'CVE_LENGUA',
    		'CVE_CANT',
    		'REPATRIADO',
    		'CVE_TIEMPO_RADICAR',
    		'ES_VICTIMA',
    		'DELITO_CUAL',
    		'CVE_ENFERMEDAD',
    		'OTRA_ENFERMEDAD',
    		'EMBARAZADA',
    		'EMBARAZADA_MESES',
    		'CVE_DISCAPACIDAD',
    		'CVE_INST_SALUD',
    		'CVE_ORFANDAD',
    		'CVE_GRADO_ESTUDIOS',
    		'DESC_CCT',
    		'TIPO_ZONA',
    		'TRABAJA',
    		'CVE_TIPO_EMPLEO',
    		'CVE_ACTIVIDAD_LABORAL',
    		'CVE_SALARIO',
    		'ALGUN_INGRESO',
    		'ALGUN_INGRESO_TIPO',
    		'ALGUN_INGRESO_MONTO',
    		'ALQUILER_TERRENO',
    		'ALQUILER_TERRENO_MONTO',
    		'PENSION',
    		'PENSION_MONTO',
    		'CVE_SALARIO2',
    		'CVE_DEPEN_ECONOM',
    		'CVE_PARENTESCO2',
    		'RECIBE_APOYO',
    		'CUANTOS_APOYOS',
    		'CUAL_APOYO',
    		'CVE_CANT2',
            'TIPO_ZONA2','CVE_ACTIVIDAD','CVE_REALIZA_ACTIVIDAD','ACTIVIDAD_FUE','CVE_SALARIO3',
    		'TIPO_ZONA3',
    		'TRABAJA2',
    		'CVE_SALARIO4',
    		'ESTUDIA',
    		'RECIBE_INGRESO',
    		'CVE_SALARIO5',
    		'BECA',
    		'CVE_PER_INGRESO',
    		'MONTO_BECA',
    		'MONTO_TRANSPORTE',
    		'CVE_TIEMPO',
            'CVE_CANT3',
            'PARENTEN_GASTOS',
            'ADULTO_SINCOMIDA',
            'ADULTO_SINTIOHAMBRE',
            'MENOR_PVA',
            'ADULTO_COMIO',
            'ADULTO_PVA',
            'LIMOSNA',
            'ADULTO_SINCENAR',
            'MENOR_COMIO',
            'ADULTO_COMIOMENOS',
            'MENOR_COMIOMENOS',
            'MENOR_SINTIOHAMBRE',
            'MENOR_MENOSCOMIDA',
            'MENOR_ACOSTARHAMBRE',
            'CVE_CASADONDEVIVE_ES',
            'CVE_MATERIAL',
            'CVE_MATERIAL2',
            'CVE_MATERIAL3',
            'CUARTOS',
            'CUARTOS_DORMIR',
            'CVE_SERVICIO_AGUA',
            'EXCUSADO',
            'SANITARIO',
            'CVE_SERVICIO_SANDREN',
            'CVE_SERVICIO_SANDREN2',
            'CVE_SERVICIO_SANDREN3',
            'CVE_SERVICIO_LUZ',
            'CVE_COMBUSTIBLE',
            'FOGON',
            'LAVADERO',
            'TARJA',
            'REGADERA',
            'TINACO',
            'CISTERNA',
            'PILETA',
            'CALENTADOR_SOLAR',
            'CALENTADOR_GAS',
            'MEDIDOR_LUZ',
            'BOMBA_AGUA',
            'TANQUE_GAS',
            'AIRE_ACOND',
            'CALEFACCION',
            'CVE_CANT4',
            'CVE_CASADONDEVIVE_ES2',
            'AFECTADA',
            'FENOMENO',
            'CVE_ARBOL',
            'FECHA_REG',
            'USU',
            'PW',
            'IP',
            'FECHA_M',
            'USU_M',
            'PW_M',
            'IP_M',
            'CVE_ORIGEN'
    ];
}
